/* CRISTARIVA — récit guidé par l'intention v5.6 : narration continue pour 1, 3 et 5 cartes. */
const CRISTARIVA_QUESTION_INTENT_STORY_VERSION='5.6';
function cr53Esc(v){try{return typeof cr52Esc==='function'?cr52Esc(v):typeof cr51Esc==='function'?cr51Esc(v):String(v??'');}catch(e){return String(v??'');}}
function cr53Question(){return String(state?.question||'').replace(/\s+/g,' ').trim();}
function cr53IsDesireQuestion(q=cr53Question()){return /\b(envie\w*|désir\w*|desir\w*|souhait\w*|aspiration\w*|attente\w*|ce que je veux|ce que j['’]aimerais|want\w*|wish\w*|desire\w*|aspiration\w*)\b/i.test(String(q||''));}
function cr54IsLifeStageQuestion(q=cr53Question()){return /\b(prochaine?s?\s+étape?s?|étape?s?\s+de\s+(?:ma|la)\s+vie|suite\s+de\s+ma\s+vie|avenir\s+de\s+ma\s+vie|chemin\s+de\s+vie|trajectoire|parcours\s+de\s+vie|évolution\s+de\s+ma\s+vie)\b/i.test(String(q||'').toLowerCase());}
function cr53CardName(c,en=false){return String(en?(c?.en?.name||c?.name||''):(c?.name||''));}
function cr53CardText(c,en=false){try{const s=typeof cr51Scope==='function'?cr51Scope():'spirit',l=en?(c?.en||{}):(c||{});return String(s==='work'?(l.reading_professionnel||l.meaning||l.definition||''):s==='relation'?(l.reading_relationnel||l.meaning||l.definition||''):(l.reading_spirituel||l.meaning||l.definition||'')).replace(/\s+/g,' ').trim();}catch(e){return '';}}
function cr53Hay(c,en=false){return (cr53CardName(c,en)+' '+cr53CardText(c,en)).toLowerCase();}
function cr53Roles(n){return n===1?['outcome']:n===3?['origin','evolution','outcome']:['origin','obstacle','resource','evolution','outcome'];}
function cr53Cap(s){s=String(s||'').trim();return s?s.charAt(0).toLocaleUpperCase()+s.slice(1):'';}
function cr53Join(a){const o=[];for(const x of a){const t=String(x||'').replace(/\s+/g,' ').replace(/[.\s]+$/,'').trim();if(!t)continue;const k=t.toLowerCase();if(!o.some(y=>y.k===k))o.push({k,t:cr53Cap(t)});}return o.map(x=>x.t).join('. ')+(o.length?'.':'');}
function cr53Clause(c,r,en=false){const h=cr53Hay(c,en);if(en){if(/fear|anx|worr|doubt/.test(h))return r==='origin'?'your expectations are partly shaped by a need for reassurance and by the wish to keep uncertainty from taking over':'fear or anticipation can distort what you really want if they speak louder than the facts';if(/control|grip|constraint|pressure|dominat/.test(h))return 'pressure, influence or habit can blur your wishes when they begin to decide in your place';if(/communicat|dialog|message|word|exchange/.test(h))return 'putting your needs into precise words helps separate a genuine desire from an assumption or projection';if(/cycle|repeat|pattern/.test(h))return 'recognising what keeps repeating in your expectations gives you the possibility of choosing differently';if(/direction|choice|decision|path/.test(h))return 'what deserves to be pursued is what gives you a coherent direction rather than what only answers present anxiety';if(/joy|pleasure|happ/.test(h))return 'what you want is closely linked to recovering genuine pleasure, lightness and momentum';if(/truth|integr|honest|clear/.test(h))return 'greater clarity about your motives helps separate a lasting desire from a passing reaction';if(/change|transform|renew|birth|reset|opening/.test(h))return 'your expectations are changing form and becoming easier to identify and act on';return r==='obstacle'?'some pressure or ambiguity still makes it harder to identify what you truly want':r==='resource'?'you already have a useful point of support for separating an essential need from a passing impulse':r==='evolution'?'your expectations can become more precise as the situation becomes easier to read':'what matters most is the direction that remains coherent when the whole situation is considered';}
if(/peur|anxi|inqui|doute/.test(h))return r==='origin'?'vos attentes semblent en partie nourries par un besoin de sécurité et par la volonté d’éviter que l’incertitude ne prenne trop de place':'la peur ou l’anticipation peuvent déformer ce que vous voulez réellement si elles prennent plus de place que les faits';if(/emprise|contrainte|pression|dépendance|dependance|domination|contrôle|controle/.test(h))return 'ce qui peut brouiller vos attentes est le risque de laisser une contrainte, une influence ou une habitude décider à votre place';if(/communication|dialogue|message|parole|échange|echange|mots précis/.test(h))return 'mettre des mots précis sur ce que vous ressentez et attendez vous aide à distinguer un désir réel d’une supposition ou d’une projection';if(/cycle|répét|repet|schéma|schema|séquence|sequence/.test(h))return 'reconnaître ce qui se répète dans vos attentes vous donne la possibilité de choisir autrement au lieu de reproduire le même schéma';if(/direction|choix|décision|decision|cap|orientation/.test(h))return 'ce qui mérite d’être poursuivi est ce qui vous donne un cap cohérent, plutôt que ce qui répond seulement à l’inquiétude du moment';if(/joie|plaisir|bonheur|légèret|legeret/.test(h))return 'ce que vous désirez est fortement lié au besoin de retrouver une satisfaction réelle, de la légèreté et un sentiment d’élan vivant';if(/vérité|verite|intégr|integr|honnêt|honnet|clair|lucid/.test(h))return 'la lucidité sur vos motivations permet de distinguer un désir durable d’une réaction passagère';if(/transformation|renouveau|naissance|changement|reset|ouverture|débloc|debloc/.test(h))return 'vos attentes changent de forme et deviennent plus faciles à identifier, à nommer et à assumer';return r==='obstacle'?'une pression ou une ambiguïté rend encore difficile l’identification de ce que vous voulez réellement':r==='resource'?'vous disposez déjà d’un point d’appui utile pour distinguer un besoin essentiel d’une impulsion passagère':r==='evolution'?'vos attentes deviennent plus précises à mesure que la situation devient plus lisible':'ce qui compte le plus est l’orientation qui reste cohérente lorsque l’ensemble de la situation est considéré';}
function cr53DesireStory(cards,en=false){const r=cr53Roles(cards.length);return cr53Join(cards.slice(0,r.length).map((c,i)=>cr53Clause(c,r[i],en)));}
function cr54LifeStageClause(c,r,en=false){const h=cr53Hay(c,en);if(en){if(/fear|block|delay|stagn|doubt/.test(h))return 'what still holds you back needs to be recognised clearly so that it no longer determines your next choices';if(/control|constraint|pressure|dominat/.test(h))return 'more autonomy becomes possible when you identify what is maintained by pressure rather than genuine choice';if(/communicat|dialog|exchange|connection/.test(h))return 'clearer exchanges and more direct connections can become a strong source of renewed movement';if(/cycle|repeat|pattern/.test(h))return 'recognising a familiar pattern allows you to decide whether it still deserves a place in your life';if(/direction|choice|decision|path/.test(h))return 'a clearer direction emerges when your choices stay aligned with what has become essential';if(/heal|repair|peace|soothe/.test(h))return 'emotional repair leaves more room for calm, confidence and a lighter way forward';if(/change|transform|renew|birth|reset/.test(h))return 'an older way of functioning is losing relevance and making room for a more current organisation of your life';return r==='outcome'?'the overall movement points toward a clearer and more coherent direction':'the situation is reshaping the conditions in which your next choices will be made';}
if(/peur|bloc|retard|stagn|doute/.test(h))return 'ce qui vous freine encore doit être reconnu clairement afin de ne plus déterminer la direction de vos prochains choix';if(/emprise|contrainte|pression|dépendance|dependance|domination|contrôle|controle/.test(h))return 'une manière d’agir plus autonome devient possible lorsque vous identifiez ce qui est maintenu par contrainte plutôt que par choix réel';if(/communication|dialogue|message|échange|echange|connexion|contact/.test(h))return 'des échanges plus clairs et des liens plus directs peuvent devenir un moteur important d’un nouvel élan';if(/cycle|répét|repet|schéma|schema|séquence|sequence/.test(h))return 'reconnaître un schéma déjà connu vous permet de décider s’il a encore sa place dans votre vie';if(/direction|choix|décision|decision|cap|orientation/.test(h))return 'une direction plus nette se dégage lorsque vos choix restent alignés avec ce qui est devenu essentiel pour vous';if(/guérison|guerison|répar|repar|apais|douceur|paix/.test(h))return 'une réparation émotionnelle laisse davantage de place à l’apaisement, à la confiance et à une manière plus légère d’avancer';if(/transformation|changement|renouveau|naissance|reset/.test(h))return 'un ancien mode de fonctionnement perd de son importance et laisse place à une organisation de vie plus adaptée à ce que vous êtes devenu';return r==='outcome'?'le mouvement d’ensemble conduit vers une direction plus claire et plus cohérente':'la situation redéfinit les conditions dans lesquelles vos prochains choix pourront se faire';}
function cr54LifeStageStory(cards,en=false){const r=cr53Roles(cards.length);return cr53Join(cards.slice(0,r.length).map((c,i)=>cr54LifeStageClause(c,r[i],en)));}
const cr53BaseStoryInterpretation=typeof storyInterpretation==='function'?storyInterpretation:null;
if(cr53BaseStoryInterpretation){storyInterpretation=function(cards){if(!Array.isArray(cards)||!cards.length)return '';const q=cr53Question(),en=state?.lang==='en';let s='';if(cr54IsLifeStageQuestion(q))s=cr54LifeStageStory(cards,en);else if(cr53IsDesireQuestion(q))s=cr53DesireStory(cards,en);if(s){const question=`<p class="reading-question">${en?'Your question':'Votre question'} : « ${cr53Esc(q)} »</p>`;return `<div class="story-reading" data-story-engine="${CRISTARIVA_QUESTION_INTENT_STORY_VERSION}"><h3>${en?'The story told by your cards':'L’histoire racontée par vos cartes'}</h3>${question}<p class="story-continuous">${s}</p></div>`;}return cr53BaseStoryInterpretation(cards);};interpretation=function(cards){return storyInterpretation(cards);};}
(function(){try{if(state?.draw?.length){for(const id of ['reading','interpretation','readingResult','story','result']){const e=document.getElementById(id);if(e&&/L’histoire racontée par vos cartes|The story told by your cards/.test(e.textContent||'')){e.innerHTML=storyInterpretation(state.draw);break;}}}}catch(e){}})();