const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const api=require('../relation-context.js');
const root=path.join(__dirname,'..');
test('FR/EN: known, new, ambiguous and negated alternatives',()=>{
  for(const s of ['Une personne déjà connue revient dans votre vie.','Votre relation actuelle réclame de la patience.','Your existing relationship needs attention.'])assert.equal(api.classify(s),'known',s);
  for(const s of ['Une nouvelle rencontre se dessine.','Quelqu’un de nouveau entre dans votre vie.','Someone you do not know will approach.'])assert.equal(api.classify(s),'new',s);
  for(const s of ['Une ouverture est possible.','Une nouvelle rencontre ou une personne déjà connue.','Pas de nouvelle rencontre annoncée.'])assert.equal(api.classify(s),'ambiguous',s);
  assert.equal(api.classify('Pas de nouvelle rencontre : votre partenaire reste au cœur du récit.'),'known');
  assert.equal(api.context('Une nouvelle rencontre se dessine.','Mon ex reviendra-t-il ?'),'new');
});
test('actual relationship deck: incompatible roles excluded, flexible roles retained',()=>{
  const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  const cards=JSON.parse(html.match(/"relation":(\[.*?\]),"dating"/)[1]);
  const known=api.filter(cards,'known').map(c=>c.id);
  const fresh=api.filter(cards,'new').map(c=>c.id);
  assert(!known.includes(106));assert(!known.includes(100));assert(known.includes(102));
  for(const id of [96,98,102,103,105,108,110,112])assert(!fresh.includes(id));
  for(const id of [100,106,113,115])assert(fresh.includes(id));
  assert.equal(api.filter(cards,'ambiguous').length,20);
});
test('shared click handler: domain filter, pending narrative and late invalidation',async()=>{
  const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
  const dom=new JSDOM('<div id="reading"></div><button id="relationBtn"></button><div id="relationResult"></div><div id="synthesis" class="hidden"></div>',{runScripts:'outside-only'});
  const w=dom.window;
  w.eval(fs.readFileSync(path.join(root,'relation-context.js'),'utf8'));
  w.eval(`var state={oracle:'cristariva',domain:'Sentimental',question:'',lang:'fr',relation:null};var DATA={relation:Array.from({length:20},(_,i)=>({id:96+i}))};var $=s=>document.querySelector(s);var rand=a=>a.slice(0,1);var cardHTML=c=>String(c.id);var t=x=>x;var renderSynthesis=()=>{};`);
  w.eval(html.slice(html.indexOf('const CRISTARIVA_RELATION_IDS='),html.indexOf("$('#dateBtn').addEventListener")));
  const reading=w.document.querySelector('#reading'),button=w.document.querySelector('#relationBtn');
  reading.innerHTML='<div data-story-engine="external-pending"><p class="story-continuous">Votre récit est en cours de rédaction…</p></div>';
  await new Promise(r=>w.setTimeout(r,0));assert(button.disabled);
  const story=reading.firstChild;
  story.querySelector('p').textContent='Une nouvelle rencontre se dessine.';story.dataset.storyEngine='external';
  await new Promise(r=>w.setTimeout(r,0));assert(!button.disabled);
  button.click();assert.equal(w.eval('state.relation.id'),100);
  assert.deepEqual(Array.from(w.eval('eligibleRelationCards().map(c=>c.id)')),[100,106,113]);
  story.querySelector('p').textContent='Votre partenaire et votre histoire commune sont au centre du récit.';
  await new Promise(r=>w.setTimeout(r,0));assert.equal(w.eval('state.relation'),null);
  button.click();assert.equal(w.eval('state.relation.id'),96);
  w.eval("state.domain='Professionnelle / Projet'");
  assert(!Array.from(w.eval('eligibleRelationCards().map(c=>c.id)')).includes(106));
  w.eval(fs.readFileSync(path.join(root,'oracle-amour-data.js'),'utf8'));
  w.eval("state.oracle='amour';state.domain='Sentimental'");
  story.querySelector('p').textContent='Une personne nouvelle arrive.';
  await new Promise(r=>w.setTimeout(r,0));
  assert.deepEqual(Array.from(w.eval('eligibleRelationCards().map(c=>c.id)')),[62,69]);
  button.click();assert.equal(w.eval('state.relation.id'),62);
  story.querySelector('p').textContent='Une personne déjà connue revient.';
  await new Promise(r=>w.setTimeout(r,0));assert.equal(w.eval('state.relation'),null);
  button.click();assert.equal(w.eval('state.relation.id'),61);
  dom.window.close();
});
